### ISSUE TITLE
does it support older version of @playwright/test?

### ISSUE THREAD

**Issue by normanlei0901** [sand4rt/playwright-ct-web#1]
@sand4rt 
my project is using @playwright/test:1.23.2 across the whole project, wonder if it works compatibly. If not, what is the version required? thanks

**Comment by sand4rt** [comment]
Good question, will get back to it  but v1.29.1 works for sure.

**Comment by sand4rt** [comment]
Ran the test on v1.23.2 and it works as expected. Doesn't work on your end? Did you run `npx playwright install`?

**Comment by normanlei0901** [comment]
@sand4rt  thanks for your prompt updates. I am not able to have it running successfully even for this repo. is there any step instruction to run ct-web-lit specifically? thanks

**Comment by sand4rt** [comment]
Did you installed the packages with `pnpm install' and ran the tests with `pnpm run test`?

**Comment by normanlei0901** [comment]
> 
@sand4rt  1.23.1 seems like it was not working for me. and realized `@sand4rt/experimental-ct-web`  is integrated with 1.29.1 automatically.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/112607209/212192489-2974693e-3c32-41e4-a985-a7af0c56ef17.png">

**Comment by normanlei0901** [comment]
one more question:
is Playwright going to support lit-element purely? Seems like its entry point is vite for this package

**Comment by sand4rt** [comment]
> > 
> 
> @sand4rt  1.23.1 seems like it was not working for me. and realized `@sand4rt/experimental-ct-web`  is integrated with 1.29.1 automatically.
> 
> <img width="373" alt="image" src="https://user-images.githubusercontent.com/112607209/212192489-2974693e-3c32-41e4-a985-a7af0c56ef17.png">
> 
> 
> 
> 

What is not working? Do you get any errors?

**Comment by sand4rt** [comment]
> one more question:
> 
> is Playwright going to support lit-element purely? Seems like its entry point is vite for this package

The tests projects are created with Vite however Vite is not required

**Comment by normanlei0901** [comment]
> 
getting below error:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/112607209/212392705-916ee73f-4336-4bb1-bc5e-4e3ff7bcd4e8.png">

**Comment by normanlei0901** [comment]
> 

thanks, btw, is there any workersRollupPlugin related support?

**Comment by sand4rt** [comment]
@normanlei0901 you need at least version `1.28.0` of `@playwright/test`. Could you retry it with [v1.0.2](https://www.npmjs.com/package/@sand4rt/experimental-ct-web/v/1.0.2)?

**Comment by sand4rt** [comment]
> thanks, btw, is there any workersRollupPlugin related support?

Not exactly sure what workersRollupPlugin is? Playwright does have support for Vite plugins: https://playwright.dev/docs/test-components#q-how-can-i-use-vite-plugins

**Comment by normanlei0901** [comment]
> > thanks, btw, is there any workersRollupPlugin related support?
> 
> Not exactly sure what workersRollupPlugin is? Playwright does have support for Vite plugins: https://playwright.dev/docs/test-components#q-how-can-i-use-vite-plugins

I am getting below error while testing the component which is using web workers under the hood. Per my understanding, we might need some related plugin to rollup the web workers with component in order to component test it. Any idea? thanks
[vite:worker-import-meta-url] Could not resolve entry module "src/worker/<worker name>.worker.js".

**Comment by sand4rt** [comment]
Do you have an example Github repo which i can look at?

**Comment by sand4rt** [comment]
@normanlei0901 i'm closing this one. Feel free to open a new ticket when needed.

**Comment by sand4rt** [comment]
Could you create a separate ticket/feature request for that? Would like to know the reason.
