### ISSUE TITLE
data-attributes

### ISSUE THREAD

**Issue by Anmo** [sand4rt/playwright-ct-web#11]
With the issue #5 (PR #6) we can use any attribute, including data-attribute:
```javascript
  mount(Button, {
    attributes: {
      'data-this-is-a-data-attribute': true,
    },
  });
```

But to facilitate, we could have also a `dataAttribute` parameter:
```javascript
  mount(Button, {
    dataAttributes: {
      thisIsADataAttribute: true,
    },
  });
```

To achieve this we could have a simple function like this:
```javascript
function __pwUpdateDataAttributes(webComponent, dataAttributes = {}) {
  Object.assign(webComponent.dataset, dataAttributes)
}
```

**Comment by sand4rt** [comment]
Thank you for creating the issue! Could you tell a bit more about why this is useful for testing?

**Comment by Anmo** [comment]
sorry for the late reply

This is just a nice to have, like I said in the description, with the support for attributes on #6 we can use pass data attributes, but would be easy to use this way, because instead of writing the name of the data attribute with `-` and therefore the need for using a string, like this:
```javascript
mount(Button, {
    attributes: {
      'data-attribute-name': true,
    },
  });
  ```
  you would be able to pass a camel case name (and therefore, without being a string), like this:
  ```javascript
mount(Button, {
    dataAttributes: {
      attributeName: true,
    },
  });
  ```

**Comment by sand4rt** [comment]
> This is just a nice to have

I don't see how the behaviour of the component is tested with dataAttributes. I'm hesitant to add this because i don't want to deviate from Playwright's API unless there is a good reason.

**Comment by sand4rt** [comment]
Closed due to inactivity, feel free to create a new ticket whenever needed
