### ISSUE TITLE
Object literal may only specify known properties, and 'title' does not exist in type 'ComponentProps<Button>'

### ISSUE THREAD

**Issue by raoufswe** [sand4rt/playwright-ct-web#27]
not really sure if this is a typing issue or I'm missing something but when all properties of a web component are marked as optional such as the following: 

```
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('button-component')
export class Button extends LitElement {
  @property({ type: String })
  /// here *
  title?: string;

  render() {
    return html`<button>${this.title}</button>`;
  }
}
```
and your test looks like the following: 

```
import { test, expect } from '@sand4rt/experimental-ct-web';
import { Button } from './components/Button';

test('render props', async ({ mount }) => {
  await mount(Button, {
    props: {
      title 'Raouf',
    },
  });
});
```

typescript will throw the following error: 

<img width="644" alt="Screenshot 2023-09-21 at 15 02 21" src="https://github.com/sand4rt/playwright-ct-web/assets/28605803/58392540-b2cb-4120-a584-f804b59f985f">

we've faced this issue in most of our components at https://github.com/justeattakeaway/pie and our workaround is to use type assertion or wrap the props with `Partial` such as [here](https://github.com/justeattakeaway/pie/blob/main/packages/components/pie-card-container/test/component/pie-card-container.spec.ts#L59) but unfortunately this wouldn't work as we have a component that marks all of its properties as optional and you will get the following by doing so as nothing is in common between both types.

<img width="644" alt="Screenshot 2023-09-21 at 15 18 37" src="https://github.com/sand4rt/playwright-ct-web/assets/28605803/7d8b0ef8-6af3-4c92-9994-c96dbb38e479">

**Comment by raoufswe** [comment]
thank you @sand4rt. in case it helps, I have used [this workaround](https://github.com/justeattakeaway/pie/pull/820/files#diff-984f3c70903729545e2634f008642004cead51fd388358c96cbfb40357d3fddbR15) on my end for now 
please let me know if you need any more details or help 💯

**Comment by sand4rt** [comment]
Hey @raoufswe, this should be fixed when you upgrade to version 1.38.0

**Comment by raoufswe** [comment]
thank you @sand4rt for your swift action, we will upgrade to the latest version 💯

**Comment by sand4rt** [comment]
Closing as per above, please feel free to open a new issue if this does not fix the issue.
