### ISSUE TITLE
Example in monorepo works, can't get it too work on my own project or clean vite install.

### ISSUE THREAD

**Issue by herrKlein** [sand4rt/playwright-ct-web#38]
Would love to use this to unit test my lit components. 

I first tried it on my own project by initializing this 
```npm init playwright-sand4rt@latest -- --ct```

I create the example `Button.ts` and `Button.test.ts`,
first error was: 
```Error: Unsupported decorator location: field```
Solved this by adding accessor
```
  @property({ type: String })
  -title!: string;
  +accessor title!: string;
```
It compiled, but next was this error: 
```
Error: TypeError: Cannot read properties of undefined (reading 'toUpperCase')
at __pwResolveComponent (http://localhost:3100/assets/index-8c01864d.js:199:46)
```

I then downloaded `playwright-ct-web` to test the `ct-web-lit` exampled.
This ran correctly inside the monorepo
I tried moving the ct-web-lit outside the monorep, 
replaced this line: 
```json
-"@sand4rt/experimental-ct-web": "workspace:*",
+"@sand4rt/experimental-ct-web": "^1.41.0",
```
To have a standalone working version, this failed due to this error:

<img width="702" alt="Screenshot 2024-01-28 at 11 33 54" src="https://github.com/sand4rt/playwright-ct-web/assets/6085660/c2b55814-9074-4fe7-abf5-6e4731fde796">

I also created a clean vite-lit repo, installed your testing lib: 
```npm init playwright-sand4rt@latest -- --ct```
Copied the button example and test of the readme, got almost the same error:
<img width="827" alt="Screenshot 2024-01-28 at 11 40 42" src="https://github.com/sand4rt/playwright-ct-web/assets/6085660/1037c4ef-660a-41ec-a01c-b5e9dd84b60c">

I would really like this to work, to unit test my lit components in playwright.

Could you shed some light why your ct-web-lit is working in the monorepo, but I can't get any test to work with the initialize

**Comment by sand4rt** [comment]
Hi @herrKlein, thanks for reporting. I'll look into it.

Does an older version of the lib work?

**Comment by herrKlein** [comment]
I tried it with version 39.0. Produces the same error.
It seems its something with rendering the react component. Trying to figure out why the monorepo version works and my clean vite install isn't?

**Comment by fajar-apri-alaska** [comment]
+1
Leaving my trace here because I also have the exact same issue.

**Comment by sand4rt** [comment]
A temporary workaround is to give the components which are imported in a test file a suffix e.g., change `Button.ts` to `Button.component.ts`.

**Comment by sand4rt** [comment]
Should be fixed in the latest version. Feel free to create a new issue otherwise
