### ISSUE TITLE
Please publish v1.45.1

### ISSUE THREAD

**Issue by jan-molak** [sand4rt/playwright-ct-web#46]
Hi @sand4rt and thanks for your work on this plugin!

It seems like version 1.45.1 is [stuck in the pipeline](https://github.com/sand4rt/playwright-ct-web/actions/runs/9794409668) because of registry.npmjs.org timeouts.
Do you think you could try to re-run the pipeline and publish the latest version to NPM?

Thank you!

**Comment by sand4rt** [comment]
done

**Comment by jan-molak** [comment]
Wow, thanks for the quick response! 🚀
